"""add pr lifecycle columns

Revision ID: 4953f2ebc81e
Revises: 53ff166f0fde
Create Date: 2026-03-12 15:05:13.399961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4953f2ebc81e'
down_revision: Union[str, Sequence[str], None] = '53ff166f0fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('is_draft', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('pull_requests', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('pull_requests', 'merged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('pull_requests', 'merge_commit_sha',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pull_requests', 'merge_commit_sha',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('pull_requests', 'merged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('pull_requests', 'closed_at')
    op.drop_column('pull_requests', 'is_draft')
    # ### end Alembic commands ###
